#ifndef GLOBAL_H
#define GLOBAL_H

class AreaLight;
class AxisAlignedBox;
class BiDiPathTracingIntegrator;
class BinaryMaterial;
class BVHNode;
class Camera;
class Conelight;
class CSGIntersection;
class CSGObject;
class DarkMatter;
class DiffuseMaterial;
class Film;
class HitRecord;
class Integrator;
class Intersectable;
class IntersectableInstance;
class IntersectableList;
class IntersectionParamter;
class JitteredSampler;
class Light;
class Material;
class MetropolisRenderer;
class MetropolisSample;
class MirrorMaterial;
class ObjReader;
class Path;
class PerPixelRenderer;
class PhongMaterial;
class Plane;
class PointLight;
class Quad;
class Ray;
class Renderer;
class Sample;
class Sampler;
class Scene;
class SimpleIntegrator;
class Spectrum;
class Sphere;
class Tonemapper;
class Triangle;
class UniDiPathTracingIntegrator;

struct ast_list;
struct ast_sphere;
struct ast_box;
struct ast_quad;
struct ast_vector;
struct ast_diffuse_material;

#endif // GLOBAL_H
